doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                mapping_types:
                    enum: string
                server_version: '%env(DATABASE_VERSION)%'
                url: '%env(resolve:DATABASE_URL)%'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
            logging:
                driver: pdo_mysql
                mapping_types:
                    enum: string
                url: '%env(resolve:DATABASE_LOG_URL)%'
                charset: utf8mb4
        types:
            my_datetime: App\Type\MyDateTimeType
            my_json: App\Type\MyJsonType
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Main:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: Main
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
            logging:
                connection: logging
                mappings:
                    Logging:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Logging'
                        prefix: 'App\Entity\Logging'
                        alias: Logging
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system