jms_serializer:
    handlers:
        datetime:
            default_format: 'Y-m-d H:i:s'
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    default_context:
        serialization:
            enable_max_depth_checks: true
            serialize_null: true
            groups:
                - naver.talktalk.cs
                - naver.talktalk.cs.comment
                - user.list
#    metadata:
#        auto_detection: false
#        directories:
#            any-name:
#                namespace_prefix: "My\\FooBundle"
#                path: "@MyFooBundle/Resources/config/serializer"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"

when@prod:
    jms_serializer:
        visitors:
            json_serialization:
                options:
                    - JSON_UNESCAPED_SLASHES
                    - JSON_PRESERVE_ZERO_FRACTION

when@dev:
    jms_serializer:
        visitors:
            json_serialization:
                options:
                    - JSON_PRETTY_PRINT
                    - JSON_UNESCAPED_SLASHES
                    - JSON_PRESERVE_ZERO_FRACTION
