monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - file

when@dev:
    monolog:
        handlers:
            file:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: error
                channels: ['file']
                max_files: 50
            main:
                type: service
                id: App\Monolog\Handler\DatabaseHandler
                level: error
                channels: ["!event", "!file", "!php"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            file:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: error
                channels: ['file']
                max_files: 50
            main:
                type: service
                id: App\Monolog\Handler\DatabaseHandler
                level: error
                channels: ["!event", "!file", "!php"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
